name: Generate Streak Stats

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats
        uses: muhammad-fiaz/github-readme-streak-stats@v1.0.1
        with:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: dark
          OUTPUT_PATH: streak-stats/github-streak-stats.svg
          RING: "A855F7"
          FIRE: "A855F7"
          CURR_STREAK_NUM: "A855F7"
          HIDE_BORDER: "true"

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f streak-stats/github-streak-stats.svg
          # Only commit if there are changes
          git diff --staged --quiet || git commit -m "Auto-generate GitHub Streak Stats"
          git push
